usernames=["csuauftiktok", "connectcdu", "afd.offiziell", "spd_pwp", "spdlingen", "spdberlin", "spd_bawue",
  "deinespd", "nrwspd", "saarspd", "spdniedersachsen", "spd_hamburg", "spd.mv", "spdsh", "insidecdu", "cdununkirchen", 
  "cdu_rade", "cdu_hessen", "cdurlp", "cdu_hamburg", "cdu_thueringen", "cdu.sachsen", "cdubrandenburg", "cdu.mv", "cdu_bw", "die.linke", "linkeessen", "dielinkelsa",
  "linke.sh", "dielinke_bremen", "die_linke_hessen", "die_linke_hl", "die_linke_th",
  "die_linke_bayern", "dielinke.sachsen", "die.linke.rlp", "die.linke.hamburg", "dielinkeberlin",
  "dielinkebw", "die_linke_brandenburg", "diegruenen", "gruene_th", "gruenenrw", "gruene_hamburg",
  "gruene_berlin", "gruenebayern", "gruenehessen", "gruenebbg", "gruenesachsen", "gruenerlp",
  "gruene_lsa", "diegruenensh", "gruene_dortmund", "gruenemuenster", "afd.nrw",
  "afdhessen", "afd.bayern", "afd_brandenburg", "afd.niedersachsen", "afd.thueringen",
  "afdsaarland", "afdsachsen", "afdelmshorn", "afdkreispinneberg", "afd.reinickendorf",
  "lars.klingbeil", "metinhakverdi1", "katja.mast", "baerbelbas", "marja.voellers",
  "doromartin", "jenszspd", "josephineortlebmdb", "bernharddaldrup", "dirkheidenblut",
  "frank.schwabe", "lenibreymaier", "johannesschraps", "annikaklose", "parsa.marvi",
  "mesarosch", "carmenwegge", "kuehnikev", "johannesarlt", "jakob_blankenburg",
  "kevinleiserhohenlohe", "esralimbacher", "erikvonmalottki", "takis_mehmetali",
  "yeone_rhie", "johannesschaetzl", "deryatuerknachbaur", "verenahubertz",
  "danielschneidercuxhaven", "frankschwabe", "elisabeth.kaiser.th", "carloskaspermdb",
  "emilyimbundestag", "rasha_nasr_", "macit_mdb", "dirkwiesespd", "armand_zorn",
  "franziska.mascheck", "jan.plobner", "danielrinkertspd", "lars.castellucci",
  "mdbaldy", "luizalicinabode", "andreas_schwarz_mdb", "stammfima",
  "isabel.cademartori", "matthias.miersch", "timkluessendorf", "dr.christos.pantazis",
  "matthias.mieves", "markus_huempfer", "dunja.kreiser", "reem.alabali",
  "baerbel.kofler", "anettekramme", "bundesbartz", "chemnitzmueller", "fjunge",
  "stefan_schwartze", "danieladeridder", "thereallenzii", "chris_schreider",
  "stefan.spd", "jens.peick.mdb", "j.saathoff", "helmut.kleebank",
  "bundestagsabgeordnete", "mathias.papendieck", "ariane.fscher", "aydanoezoguz",
  "josip.mdb", "fabianfunke.spd", "guelistan.yueksel.mdb", "karl_lauterbach_privat",
  "stuewer", "peggy.ist.da", "tina.rudolph.spd", "anna.kassautzki",
  "rebecca.schamber", "anke_hennig_bundestag", "heikeheubachspd", "nadja.sthamer",
  "linaseitzl", "kristianklinck", "dirk.ulrich.mende", "siemtje_moeller",
  "dieschmidtspd", "ritahaglkehl", "politikmitkaramba", "sonja.eichwede",
  "simonakossmdb", "mathias_stein", "jessi_rosenthal", "katrin.zschau",
  "hakandemirnk", "timo.schisanowski", "nadinerufmdb", "natalie.pawlik.mdb",
  "martindiedenhofenmdb", "doering.felix", "bestphal5", "dr.thorsten.rudolph",
  "fiedelseb", "bengt.bergt", "ingo.schaefer.spd", "nils.schmid.spd",
  "dr.wollmann", "martin.rabanus", "jasmina.hostert", "brian.nickholz",
  "michellemuente", "teamolafscholz", "michael.schrodi", "marianneschiedermdb",
  "sonke.rix", "wiebkepapenbrock", "holgermannle", "nezahatbaradari",
  "katrin.budde", "tanjamachts", "timon.gremmels", "jandieren",
  "kthrn_mchl_spd", "svenja_schulze", "bettina.lugk", "rohdedennis",
  "oliver.kaczmarek25", "adis.93", "luciaschanbacher", "sanaeabdi_koeln",
  "claudia_moll", "michael.schrodi", "christoph.schmid.mdb", "sebastian_hartmann",
  "wiebke.esdar",
  "dorobaer", "ulmer_ronja", "olav.gutting", "johannes.steiniger", "fabian_gramling",
  "user723357909253568", "katja.leikert", "catarina_mdb", "stephanalbanimdb",
  "thomas.gebhart", "0711max", "bjoernsimon.mdb",
  "der_geissler", "matthias.hauer.mdb",
  "simone.borchardt", "thomas.erndl", "merzcdu", "andreasmattfeldt", "sepp.mueller",
  "drpeterramsauer1", "alexander.hoffmann_mdb", "vmayerlay", "volkerullrich",
  "susannehierl", "anne.koenig", "mk85930", "nicolaszippelius", "fabian_gramling",
  "yannick_bury", "anja.weisgerber", "silviabreher1", "silkelaunert",
  "steffenbilgermdb", "michael.frieser.mdb", "george_kippele", "mario.czaja",
  "stumpp_christina", "peter_aumer", "mek_englhardtkopf", "florian_mueller_mdb",
  "anne_janssen_26", "jensspahn", "paulziemiak", "klausmackmdb", "felix.schreiner",
  "alois.rainer.mdb", "juliakloeckner", "marc.henrichmann", "petra.nicolaisen",
  "christoph.ploss", "team.anja", "thomasbareiss", "gunther_krichbaum",
  "tilmankuban", "mechthild_heil", "dietrich_monstadt.cdu", "alex.throm",
  "patrick.schnieder", "thomas.silberhorn", "nadine.schn36", "carsten.mueller.c",
  "thorstenfrei", "jana.schimke",
  "pellmann", "heidireichinnek", "gesineloetzsch1", "janine_wissler",
  "bundestagsperli", "martinarennermdb", "clara_buenger", "dietmarbartsch",
  "atesguerpinar", "dielinkekathrin", "susanne_ferschl", "goekayakbulut",
  "gregorgysi48", "caren.lay.mdb", "susanneferschl",
  "amtsberg.luise_mdb", "bruno.hoenel", "debbieduering", "langricarda", "tbbacherle",
  "merle_spellerberg", "herr_emmerich", "denise.loop", "jpahlke", "emiliafester",
  "kathrin.henneberger", "ulle_schauws", "nyke.slawik", "karo.otte", "tessa.ganserer",
  "jamila.schaefer", "felixbanaszak", "paulapiechotta", "zoe.gruene", "hannes4future",
  "erhard.grundl.mdb", "max_lks", "badumlisa", "katharina_beck", "annaluehrmann",
  "hanna_steinmueller", "kassem.tahersaleh", "lime_green_leni", "aspallek",
  "robinwagenermdb", "matthias.gastel", "michaelsacher.mdb", "ophelianick",
  "tabearoessner", "lamyakaddor", "franziska.brantner", "cj_schroeder",
  "frauanwaeltin", "maikaussendorf", "sandradetzermdb", "kai.gehring",
  "misbah_s_khan", "janni_gesenhues", "andreas.audretsch", "benner_lukas",
  "_svenlehmann_", "till_steffen", "franziska.krumwie", "roberthabeck",
  "juergenkretz", "leckert_", "bernhard.herrmann3", "anna.christmann.mdb",
  "ekin_deligoez", "irene.mihalic", "sabine_gruetzmacher", "filiz.polat.mdb",
  "awet_tesfaiesus", "anja.liebert", "ingrid.nestle", "stefangelbhaar",
  "boris.mijatovic.mdb", "stefanwenzel_mdb", "chantalkopf", "dieterjanecek",
  "cem.oezdemir", "karl.baer.mdb", "kordula.schulzasc",
  "nicolehoechst_mdb", "brandner_afd", "juergenpohlafd", "mr_afd", "alice_weidel_afd",
  "janwenzelschmidt", "roger_beckamp", "rene_springer", "gerrithuy", "protschkasposition",
  "steffenkotre", "beatrixvonstorchneu", "jan_nolte_bundestag", "goetzfroemming",
  "kleinwaechterafd", "enricokomning", "brandesdirk", "peterfelser_mdb", "albrecht_glaser_mdb",
  "hannesgnauck", "dr.dirkspaniel", "malte.kaufmann", "stefan_keuter", "edgarnaujokmdb",
  "frank.rinck", "bernd.schattner.mdb", "eugen_schmidt.mdb", "dietmar.friedhoff.mdb",
  "joachimwundrak", "karstenhilseafd", "sichertdeutschland", "christinabaumafd",
  "pboehringer", "tino.chrupalla.afd", "gottfriedcurio", "thomas.ehrhorn", "kaygottschalk",
  "dr_espendiller", "markusfrohnmaier", "matthias_helferich", "kaufmannm",
  "joernkoenig_mdb", "muenzenmaier", "gerold_otten", "haraldweyel", "dr.rainer.rothfuss",
  "carolin_bachmann_mdb", "gereonbollmann"
  ]

afd_usernames = ["afd.offiziell", "afd.nrw", "afdhessen", "afd.bayern", "afd_brandenburg", 
                 "afd.niedersachsen", "afd.thueringen", "afdsaarland", "afdsachsen", "afdelmshorn", 
                 "afdkreispinneberg", "afd.reinickendorf",
                 "nicolehoechst_mdb", "brandner_afd", "juergenpohlafd", "mr_afd", "alice_weidel_afd",
  "janwenzelschmidt", "roger_beckamp", "rene_springer", "gerrithuy", "protschkasposition",
  "steffenkotre", "beatrixvonstorchneu", "jan_nolte_bundestag", "goetzfroemming",
  "kleinwaechterafd", "enricokomning", "brandesdirk", "peterfelser_mdb", "albrecht_glaser_mdb",
  "hannesgnauck", "dr.dirkspaniel", "malte.kaufmann", "stefan_keuter", "edgarnaujokmdb",
  "frank.rinck", "bernd.schattner.mdb", "eugen_schmidt.mdb", "dietmar.friedhoff.mdb",
  "joachimwundrak", "karstenhilseafd", "sichertdeutschland", "christinabaumafd",
  "pboehringer", "tino.chrupalla.afd", "gottfriedcurio", "thomas.ehrhorn", "kaygottschalk",
  "dr_espendiller", "markusfrohnmaier", "matthias_helferich", "kaufmannm",
  "joernkoenig_mdb", "muenzenmaier", "gerold_otten", "haraldweyel", "dr.rainer.rothfuss",
  "carolin_bachmann_mdb", "gereonbollmann"]

spd_usernames = ["spd_pwp", "spdlingen", "spdberlin", "spd_bawue", "deinespd", "nrwspd", "saarspd", "spdniedersachsen", "spd_hamburg", "spd.mv", "spdsh",
                 "lars.klingbeil", "metinhakverdi1", "katja.mast", "baerbelbas", "marja.voellers",
  "doromartin", "jenszspd", "josephineortlebmdb", "bernharddaldrup", "dirkheidenblut",
  "frank.schwabe", "lenibreymaier", "johannesschraps", "annikaklose", "parsa.marvi",
  "mesarosch", "carmenwegge", "kuehnikev", "johannesarlt", "jakob_blankenburg",
  "kevinleiserhohenlohe", "esralimbacher", "erikvonmalottki", "takis_mehmetali",
  "yeone_rhie", "johannesschaetzl", "deryatuerknachbaur", "verenahubertz",
  "danielschneidercuxhaven", "frankschwabe", "elisabeth.kaiser.th", "carloskaspermdb",
  "emilyimbundestag", "rasha_nasr_", "macit_mdb", "dirkwiesespd", "armand_zorn",
  "franziska.mascheck", "jan.plobner", "danielrinkertspd", "lars.castellucci",
  "mdbaldy", "luizalicinabode", "andreas_schwarz_mdb", "stammfima",
  "isabel.cademartori", "matthias.miersch", "timkluessendorf", "dr.christos.pantazis",
  "matthias.mieves", "markus_huempfer", "dunja.kreiser", "reem.alabali",
  "baerbel.kofler", "anettekramme", "bundesbartz", "chemnitzmueller", "fjunge",
  "stefan_schwartze", "danieladeridder", "thereallenzii", "chris_schreider",
  "stefan.spd", "jens.peick.mdb", "j.saathoff", "helmut.kleebank",
  "bundestagsabgeordnete", "mathias.papendieck", "ariane.fscher", "aydanoezoguz",
  "josip.mdb", "fabianfunke.spd", "guelistan.yueksel.mdb", "karl_lauterbach_privat",
  "stuewer", "peggy.ist.da", "tina.rudolph.spd", "anna.kassautzki",
  "rebecca.schamber", "anke_hennig_bundestag", "heikeheubachspd", "nadja.sthamer",
  "linaseitzl", "kristianklinck", "dirk.ulrich.mende", "siemtje_moeller",
  "dieschmidtspd", "ritahaglkehl", "politikmitkaramba", "sonja.eichwede",
  "simonakossmdb", "mathias_stein", "jessi_rosenthal", "katrin.zschau",
  "hakandemirnk", "timo.schisanowski", "nadinerufmdb", "natalie.pawlik.mdb",
  "martindiedenhofenmdb", "doering.felix", "bestphal5", "dr.thorsten.rudolph",
  "fiedelseb", "bengt.bergt", "ingo.schaefer.spd", "nils.schmid.spd",
  "dr.wollmann", "martin.rabanus", "jasmina.hostert", "brian.nickholz",
  "michellemuente", "teamolafscholz", "michael.schrodi", "marianneschiedermdb",
  "sonke.rix", "wiebkepapenbrock", "holgermannle", "nezahatbaradari",
  "katrin.budde", "tanjamachts", "timon.gremmels", "jandieren",
  "kthrn_mchl_spd", "svenja_schulze", "bettina.lugk", "rohdedennis",
  "oliver.kaczmarek25", "adis.93", "luciaschanbacher", "sanaeabdi_koeln",
  "claudia_moll", "michael.schrodi", "christoph.schmid.mdb", "sebastian_hartmann",
  "wiebke.esdar"]

cdu_csu_usernames = ["csuauftiktok", "connectcdu", "insidecdu", "cdununkirchen", "cdu_rade", "cdu_hessen", "cdurlp", "cdu_hamburg", "cdu_thueringen", "cdu.sachsen", "cdubrandenburg", "cdu.mv", "cdu_bw",
                     "dorobaer", "ulmer_ronja", "olav.gutting", "johannes.steiniger", "fabian_gramling",
  "user723357909253568", "katja.leikert", "catarina_mdb", "stephanalbanimdb",
  "thomas.gebhart", "0711max", "bjoernsimon.mdb", "der_geissler", "matthias.hauer.mdb",
  "simone.borchardt", "thomas.erndl", "merzcdu", "andreasmattfeldt", "sepp.mueller",
  "drpeterramsauer1", "alexander.hoffmann_mdb", "vmayerlay", "volkerullrich",
  "susannehierl", "anne.koenig", "mk85930", "nicolaszippelius", "fabian_gramling",
  "yannick_bury", "anja.weisgerber", "silviabreher1", "silkelaunert",
  "steffenbilgermdb", "michael.frieser.mdb", "george_kippele", "mario.czaja",
  "stumpp_christina", "peter_aumer", "mek_englhardtkopf", "florian_mueller_mdb",
  "anne_janssen_26", "jensspahn", "paulziemiak", "klausmackmdb", "felix.schreiner",
  "alois.rainer.mdb", "juliakloeckner", "marc.henrichmann", "petra.nicolaisen",
  "christoph.ploss", "team.anja", "thomasbareiss", "gunther_krichbaum",
  "tilmankuban", "mechthild_heil", "dietrich_monstadt.cdu", "alex.throm",
  "patrick.schnieder", "thomas.silberhorn", "nadine.schn36", "carsten.mueller.c",
  "thorstenfrei", "jana.schimke"]

gruene_usernames = ["diegruenen", "gruene_th", "gruenenrw", "gruene_hamburg", "gruene_berlin", "gruenebayern", "gruenehessen", "gruenebbg", "gruenesachsen", "gruenerlp", "gruene_lsa", "diegruenensh", "gruene_dortmund", "gruenemuenster",
                    "amtsberg.luise_mdb", "bruno.hoenel", "debbieduering", "langricarda", "tbbacherle",
  "merle_spellerberg", "herr_emmerich", "denise.loop", "jpahlke", "emiliafester",
  "kathrin.henneberger", "ulle_schauws", "nyke.slawik", "karo.otte", "tessa.ganserer",
  "jamila.schaefer", "felixbanaszak", "paulapiechotta", "zoe.gruene", "hannes4future",
  "erhard.grundl.mdb", "max_lks", "badumlisa", "katharina_beck", "annaluehrmann",
  "hanna_steinmueller", "kassem.tahersaleh", "lime_green_leni", "aspallek",
  "robinwagenermdb", "matthias.gastel", "michaelsacher.mdb", "ophelianick",
  "tabearoessner", "lamyakaddor", "franziska.brantner", "cj_schroeder",
  "frauanwaeltin", "maikaussendorf", "sandradetzermdb", "kai.gehring",
  "misbah_s_khan", "janni_gesenhues", "andreas.audretsch", "benner_lukas",
  "_svenlehmann_", "till_steffen", "franziska.krumwie", "roberthabeck",
  "juergenkretz", "leckert_", "bernhard.herrmann3", "anna.christmann.mdb",
  "ekin_deligoez", "irene.mihalic", "sabine_gruetzmacher", "filiz.polat.mdb",
  "awet_tesfaiesus", "anja.liebert", "ingrid.nestle", "stefangelbhaar",
  "boris.mijatovic.mdb", "stefanwenzel_mdb", "chantalkopf", "dieterjanecek",
  "cem.oezdemir", "karl.baer.mdb", "kordula.schulzasc"]

linke_usernames = ["die.linke", "linkeessen", "dielinkelsa", "linke.sh", "dielinke_bremen", "die_linke_hessen", "die_linke_hl", "die_linke_th",
  "die_linke_bayern", "dielinke.sachsen", "die.linke.rlp", "die.linke.hamburg", "dielinkeberlin",
  "dielinkebw", "die_linke_brandenburg",
  "pellmann", "heidireichinnek", "gesineloetzsch1", "janine_wissler",
  "bundestagsperli", "martinarennermdb", "clara_buenger", "dietmarbartsch",
  "atesguerpinar", "dielinkekathrin", "susanne_ferschl", "goekayakbulut",
  "gregorgysi48", "caren.lay.mdb", "susanneferschl"]

start_date = "20250101"
end_date = "20250223"